---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: indexer-tutorials
  name:  tomcat-deployment-nautilus
  labels:
    name: webdep
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webpod
      app: demo
  template:
    metadata:
      name: webpod
      labels:
        name: webpod
        app: demo
        # 这是第一个业务自定义label，指定了mysql的语言类型是c语言
        language: java
        # 这是第二个业务自定义label，指定了这个pod属于哪一类服务，tomcat属于web类
        business-service-type: web
    spec:
      containers:
        - name: tomcat-container-nautilus
          image: tomcat:11.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: indexer-tutorials
  name: tomcat-service-nautilus
spec:
  type: NodePort
  selector:
    name: webpod
    app: demo
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 32227