version: "2"

services:
  influxweb:
    image: influxdb:1.2.0
    container_name: influxweb
    environment:
      - TZ=Asia/Shanghai
      - INFLUXDB_DB=testdb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
    networks:
      - my-net
    ports:
      - 8083:8083


  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    environment:
      - TZ=Asia/Shanghai
      - INFLUXDB_DB=testdb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=123456
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
    networks:
      - my-net
    ports:
      - 8086:8086

networks:
  my-net:
    driver: bridge
