server:
  #服务端口
  port: 8086
spring:
  application:
    name: gateway-dynamic-route
  cloud:
    nacos:
      discovery:
        # nacos服务地址
        server-addr: 192.168.50.43:8848
    gateway:
      routes:
        - id: path_route
          uri: http://0.0.0.0:8082
          predicates:
          - Path=/hello/**
          filters:
            - name: BizLogicRoute
              args:
                prodEnvUri: http://127.0.0.1:8082
                testEnvUri: http://127.0.0.1:8087