server:
  port: 8083
spring:
  application:
    name: springcloud-deep-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true