server:
  port: 7772

spring:
  application:
    name: nearby-method-two
  redis:
    host: 127.0.0.1
    timeout: 3000
    password:
    port: 6379
    database: 5
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制)
        min-idle: 0 # 连接池中的最小空闲连接